"""usuarios and roles

Revision ID: 375bdd4d4bf4
Revises: c915206f0e68
Create Date: 2026-09-16 19:39:26.586164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375bdd4d4bf4'
down_revision: Union[str, Sequence[str], None] = 'c915206f0e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('ESTUDIANTE', 'DOCENTE', 'EGRESADO', name='tipo_usuario_enum'), nullable=False),
    sa.Column('estado_cuenta', sa.Enum('ACTIVA', 'INACTIVA', 'BLOQUEADA', name='estado_cuenta_enum'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('docentes',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('num_empleado', sa.String(length=30), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamentos.id_departamento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_docentes_num_empleado'), 'docentes', ['num_empleado'], unique=True)
    op.create_table('usuarios_roles',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol')
    )
    op.create_table('egresados',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('num_control', sa.String(length=20), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('anio_egreso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrera'], ['carreras.id_carrera'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_egresados_num_control'), 'egresados', ['num_control'], unique=True)
    op.create_table('estudiantes',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('num_control', sa.String(length=20), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_carrera'], ['carreras.id_carrera'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_estudiantes_num_control'), 'estudiantes', ['num_control'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estudiantes_num_control'), table_name='estudiantes')
    op.drop_table('estudiantes')
    op.drop_index(op.f('ix_egresados_num_control'), table_name='egresados')
    op.drop_table('egresados')
    op.drop_table('usuarios_roles')
    op.drop_index(op.f('ix_docentes_num_empleado'), table_name='docentes')
    op.drop_table('docentes')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('roles')
    # ### end Alembic commands ###
