"""add department managers

Revision ID: 60b864d49cf7
Revises: 375bdd4d4bf4
Create Date: 2026-09-16 21:19:51.511448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b864d49cf7'
down_revision: Union[str, Sequence[str], None] = '375bdd4d4bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsables_departamento',
    sa.Column('id_responsable', sa.Integer(), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('id_usuario_docente', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamentos.id_departamento'], ),
    sa.ForeignKeyConstraint(['id_usuario_docente'], ['docentes.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_responsable')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsables_departamento')
    # ### end Alembic commands ###
