"""add project integrity constraints

Revision ID: 6445c8d72cb0
Revises: a6d1876ab88a
Create Date: 2026-09-20 18:33:25.340417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6445c8d72cb0'
down_revision: Union[str, Sequence[str], None] = 'a6d1876ab88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_orden_autor_por_proyecto', 'proyectos_autores', ['id_proyecto', 'orden_autoria'], unique=True, postgresql_where=sa.text("tipo_participacion = 'AUTOR'"))
    op.create_index('uq_responsable_activo_departamento', 'responsables_departamento', ['id_departamento'], unique=True, postgresql_where=sa.text('activo IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_responsable_activo_departamento', table_name='responsables_departamento', postgresql_where=sa.text('activo IS true'))
    op.drop_index('uq_orden_autor_por_proyecto', table_name='proyectos_autores', postgresql_where=sa.text("tipo_participacion = 'AUTOR'"))
    # ### end Alembic commands ###
