"""research

Revision ID: a6d1876ab88a
Revises: 60b864d49cf7
Create Date: 2026-09-16 23:14:42.194586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d1876ab88a'
down_revision: Union[str, Sequence[str], None] = '60b864d49cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas_tematicas',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_area'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('palabras_clave',
    sa.Column('id_palabra_clave', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_palabra_clave'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('proyectos',
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'EN_REVISION', 'REQUIERE_CAMBIOS', 'APROBADO', 'RECHAZADO', 'PUBLICADO', name='estado_proyecto_enum'), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamentos.id_departamento'], ),
    sa.PrimaryKeyConstraint('id_proyecto')
    )
    op.create_index(op.f('ix_proyectos_titulo'), 'proyectos', ['titulo'], unique=False)
    op.create_table('archivos',
    sa.Column('id_archivo', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('nombre_almacenado', sa.String(length=255), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('tamanio', sa.BigInteger(), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subido_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id_proyecto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_archivo'),
    sa.UniqueConstraint('nombre_almacenado')
    )
    op.create_table('historial_estados',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.Enum('BORRADOR', 'EN_REVISION', 'REQUIERE_CAMBIOS', 'APROBADO', 'RECHAZADO', 'PUBLICADO', name='estado_proyecto_enum'), nullable=True),
    sa.Column('estado_nuevo', sa.Enum('BORRADOR', 'EN_REVISION', 'REQUIERE_CAMBIOS', 'APROBADO', 'RECHAZADO', 'PUBLICADO', name='estado_proyecto_enum'), nullable=False),
    sa.Column('cambiado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cambiado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id_proyecto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_table('proyectos_areas',
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_area'], ['areas_tematicas.id_area'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id_proyecto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_proyecto', 'id_area')
    )
    op.create_table('proyectos_autores',
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_participacion', sa.Enum('AUTOR', 'ASESOR', 'COLABORADOR', name='tipo_participacion_enum'), nullable=False),
    sa.Column('orden_autoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id_proyecto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_proyecto', 'id_usuario')
    )
    op.create_table('proyectos_palabras_clave',
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_palabra_clave', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_palabra_clave'], ['palabras_clave.id_palabra_clave'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id_proyecto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_proyecto', 'id_palabra_clave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proyectos_palabras_clave')
    op.drop_table('proyectos_autores')
    op.drop_table('proyectos_areas')
    op.drop_table('historial_estados')
    op.drop_table('archivos')
    op.drop_index(op.f('ix_proyectos_titulo'), table_name='proyectos')
    op.drop_table('proyectos')
    op.drop_table('palabras_clave')
    op.drop_table('areas_tematicas')
    # ### end Alembic commands ###
