"""create departamentos and carreras

Revision ID: c915206f0e68
Revises: 
Create Date: 2026-09-16 19:26:41.555412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c915206f0e68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_departamento'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('carreras',
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('siglas', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamentos.id_departamento'], ),
    sa.PrimaryKeyConstraint('id_carrera'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('siglas')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carreras')
    op.drop_table('departamentos')
    # ### end Alembic commands ###
